In [22]:
import pandas as pd

In [23]:
meta_df = pd.read_csv("case study/GDP/Metadata_Country.csv")
GDP_df = pd.read_csv("case study/GDP/GDP.csv")
Pop_df = pd.read_csv("case study/Population/Population.csv")

In [24]:
Pop_df.to_csv("Data/Pop.csv")

In [25]:
GDP_df = GDP_df.drop(['Indicator Name','Indicator Code','Unnamed: 66'], axis =1)
Pop_df= Pop_df.drop(['Indicator Name','Indicator Code','Unnamed: 66'], axis =1)

In [26]:
GDP_df = pd.merge(GDP_df, meta_df)
Pop_df = pd.merge(Pop_df, meta_df)

In [27]:
Pop_df = Pop_df.drop(['Unnamed: 5','TableName','SpecialNotes'],axis = 1)
GDP_df = GDP_df.drop(['Unnamed: 5','TableName','SpecialNotes'],axis = 1)

In [28]:
Pop_df.to_csv("Data/Pop.csv")
GDP_df.to_csv("Data/GDP.csv")

In [29]:
GDP_df

,Country Name,Country Code,1960,1961,1962,1963,1964,1965,1966,1967,...,2014,2015,2016,2017,2018,2019,2020,2021,Region,IncomeGroup
0,Aruba,ABW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.791061e+09,2.963128e+09,2.983799e+09,3.092179e+09,3.202235e+09,3.310056e+09,2.496648e+09,NaN,Latin America & Caribbean,High income
1,Africa Eastern and Southern,AFE,2.129059e+10,2.180847e+10,2.370702e+10,2.821004e+10,2.611879e+10,2.968217e+10,3.223912e+10,3.351455e+10,...,1.003679e+12,9.242525e+11,8.823551e+11,1.020647e+12,9.910223e+11,9.975340e+11,9.216459e+11,1.082096e+12,NaN,NaN
2,Afghanistan,AFG,5.377778e+08,5.488889e+08,5.466667e+08,7.511112e+08,8.000000e+08,1.006667e+09,1.400000e+09,1.673333e+09,...,2.049713e+10,1.913421e+10,1.811656e+10,1.875347e+10,1.805323e+10,1.879945e+10,2.011614e+10,NaN,South Asia,Low income
3,Africa Western and Central,AFW,1.040414e+10,1.112789e+10,1.194319e+10,1.267633e+10,1.383837e+10,1.486223e+10,1.583259e+10,1.442604e+10,...,8.649905e+11,7.607345e+11,6.905464e+11,6.837487e+11,7.416899e+11,7.945430e+11,7.844457e+11,8.358084e+11,NaN,NaN
4,Angola,AGO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.372444e+11,8.721929e+10,4.984049e+10,6.897276e+10,7.779294e+10,6.930910e+10,5.361907e+10,7.254699e+10,Sub-Saharan Africa,Lower middle income
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260,Kosovo,XKX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.074658e+09,6.295820e+09,6.682833e+09,7.180813e+09,7.878509e+09,7.899879e+09,7.716925e+09,9.007159e+09,Europe & Central Asia,Upper middle income
261,"Yemen, Rep.",YEM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.322859e+10,4.244450e+10,3.131783e+10,2.684223e+10,2.160616e+10,2.188761e+10,1.884051e+10,2.106169e+10,Middle East & North Africa,Low income
262,South Africa,ZAF,8.748597e+09,9.225996e+09,9.813996e+09,1.085420e+10,1.195600e+10,1.306899e+10,1.421139e+10,1.582139e+10,...,3.811989e+11,3.467098e+11,3.235855e+11,3.814488e+11,4.048421e+11,3.879346e+11,3.354421e+11,4.199464e+11,Sub-Saharan Africa,Upper middle income
263,Zambia,ZMB,7.130000e+08,6.962857e+08,6.931429e+08,7.187143e+08,8.394286e+08,1.082857e+09,1.264286e+09,1.368000e+09,...,2.714102e+10,2.125122e+10,2.095841e+10,2.587360e+10,2.631159e+10,2.330867e+10,1.811063e+10,2.120306e+10,Sub-Saharan Africa,Low income
264,Zimbabwe,ZWE,1.052990e+09,1.096647e+09,1.117602e+09,1.159512e+09,1.217138e+09,1.311436e+09,1.281750e+09,1.397002e+09,...,1.949552e+10,1.996312e+10,2.054868e+10,1.758489e+10,1.811554e+10,1.928429e+10,1.805117e+10,2.621773e+10,Sub-Saharan Africa,Lower middle income