In [1]:
import pandas as pd

In [2]:
GDP = pd.read_csv("Data/GDP.csv")

In [3]:
GDP = GDP.drop(['Unnamed: 0',],axis = 1)

In [4]:
GDP_by_continent = GDP.groupby(by="Region").sum()
GDP_by_group = GDP.groupby(by="IncomeGroup").sum()

In [5]:
Population = pd.read_csv("Data/Pop.csv")

In [6]:
Population = Population.drop(['Unnamed: 0',],axis = 1)

In [7]:
Population_by_continent = Population.groupby(by="Region").sum()
Population_by_group = Population.groupby(by="IncomeGroup").sum()

In [8]:
continent_GDP = GDP_by_continent.div(Population_by_continent)

In [11]:
continent_GDP.transpose().to_csv("Data/GDP_Continent.csv")

In [24]:
GDP_df = pd.read_csv("case study/GDP/GDP.csv")
Pop_df = pd.read_csv("case study/Population/Population.csv")

In [28]:
GDP_df = GDP_df.drop(['Country Code','Indicator Name','Indicator Code','Unnamed: 66'], axis =1)
Pop_df= Pop_df.drop(['Country Code','Indicator Name','Indicator Code','Unnamed: 66'], axis =1)

In [30]:
GDP_df = GDP_df.set_index('Country Name')
Pop_df = Pop_df.set_index('Country Name')

In [33]:
GDPperCapita=GDP_df.div(Pop_df)

In [35]:
GDPperCapita.to_csv("Data/GDP_per_Capita.csv")

In [45]:
GDP_pct = continent_GDP.transpose().pct_change().transpose()

In [43]:
continent_GDP

,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
Region,,,,,,,,,,,,,,,,,,,,,
East Asia & Pacific,142.848749,143.504612,144.369705,157.246652,176.211595,191.988133,209.037550,225.646255,242.491197,272.135876,...,9316.379124,9342.287573,9561.000937,9455.889610,9724.315399,10309.001204,11167.726507,11339.349615,11304.120538,12816.562387
Europe & Central Asia,417.817717,438.845691,473.462489,517.105287,565.457029,608.987066,672.274791,717.380061,743.890529,815.846066,...,25119.128577,26133.757349,26374.151831,22612.850282,22443.172777,23691.687673,25284.189453,24901.317244,23906.587590,27012.136009
Latin America & Caribbean,269.579784,278.022909,401.701825,398.536526,430.061018,455.416388,488.446142,485.700713,508.253985,553.857192,...,10195.041742,10335.058724,10429.571110,8216.115479,7950.475993,8748.910388,8476.423463,8281.386826,6921.292117,7543.409793
Middle East & North Africa,134.028246,136.984649,131.926217,144.257899,154.964120,215.489532,221.483875,230.046707,302.020534,325.116733,...,8992.171694,8666.910240,8540.737206,7375.464756,7307.448457,7469.549834,7704.420769,7536.948963,6643.654940,5807.215614
North America,2939.448335,2991.592897,3155.097538,3283.141453,3480.426945,3729.969704,4044.247215,4231.867351,4579.982260,4912.487595,...,51881.170886,53234.150098,54714.470929,55452.421384,56312.434885,58430.198596,61158.563559,63175.740130,61000.855259,67514.023116
South Asia,82.937763,86.665068,90.558118,99.690597,111.672237,117.322447,96.488696,103.804033,106.374159,114.324922,...,1366.059425,1383.316909,1496.014996,1543.048131,1696.739629,1911.329754,1944.006635,1987.568340,1875.441391,2162.893661
Sub-Saharan Africa,121.305784,123.983184,131.059384,146.283113,140.186856,152.258289,160.391955,156.462779,163.300592,181.759221,...,1851.779309,1917.302443,1932.513463,1694.967450,1537.100976,1622.287453,1606.475862,1617.462464,1499.881893,1643.875723

In [47]:
GDP_pct.to_csv("Data/continent_Pct_change.csv")